services:
  email-probe:
    build: .
    container_name: email-probe
    environment:
      - DNS_SERVER=${DNS_SERVER:-8.8.8.8}  # Default to Google DNS if not specified
      - EMAIL_SERVER_IP=${EMAIL_SERVER_IP}
      - EMAIL_SERVER_HOSTNAME=${EMAIL_SERVER_HOSTNAME}
      - EMAIL_MX_DOMAIN=${EMAIL_MX_DOMAIN}
      - EMAIL_EXPECTED_MX_IP=${EMAIL_EXPECTED_MX_IP}
      - EMAIL_SERVER_HTTP_PORT=${EMAIL_SERVER_HTTP_PORT}
      - EMAIL_SERVER_HTTPS_PORT=${EMAIL_SERVER_HTTPS_PORT}
      - EMAIL_SERVER_SMTP_PORT=${EMAIL_SERVER_SMTP_PORT}
      - EMAIL_SERVER_SMTP_SECURE_PORT=${EMAIL_SERVER_SMTP_SECURE_PORT}
      - EMAIL_SMTP_USERNAME=${EMAIL_SMTP_USERNAME}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - PROBE_COLLECTION_INTERVAL=${PROBE_COLLECTION_INTERVAL}
      - METRICS_EXPORT_PORT=${METRICS_EXPORT_PORT}
    ports:
      - "${METRICS_EXPORT_PORT}:${METRICS_EXPORT_PORT}"
    dns:
      - ${DNS_SERVER:-8.8.8.8}  # Use the configured DNS server
    restart: unless-stopped
